version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/barman_build

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -e .
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -v